[font]
size = 14

[font.normal]
family = "GeistMono Nerd Font Mono"

[keyboard]
bindings = [
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
]

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[window]
decorations = "None"

[selection]
save_to_clipboard = true

